- geeksay.js
Adds some quotes:
"There are 10 types of people in the world: those who understand binary and those who don't",
"I love my life",
"I love my house",
"heart break",
"I like to fix shit"
Adds the translations:
"heart": "<3",
"love": "<3",
"like": "<3"
> Added quotes and translation

- geeksay.js
Example for translation ["send": "push]:
Input: Hey, could you send that for me?
Output: Hey, could you push that for me?
> Added a translation and quote to geeksay.js

- README.md
- cli.js
- geeksay.js
- package.json
#changes 
* supporting sentence based on conversation in issue  #81  
* updating package.json and adding `geeksay` keyword in *bin* now after linking package, user can run `geeksay` command globally in his/her machine. 
* improving readme file.
> supporting sentence and improving CLI, README

- README.md
This tripped me up as I assumed I'd need to put the message in quotes because it had spaces.
So I did `geeksay "hello world"` and wondered why it wasn't working.
> Emphasize that you shouldn't put the string in quotes for the CLI (README.md)

- geeksay.js
Removed duplicate translation for "plus": "+"
> Removed duplicate translation

- index.html
So it looks more consistent – and I don't think I can change the Twitter one since it's in an iframe.
> Made all button border radii match Twitter button border radius

- geeksay.js
issue related: 
[https://github.com/swapagarwal/geeksay/issues/5#issue-365202020](url)
> Adding a quote

- geeksay.js
> Added words to Geeksay.js

- geeksay.js
2 emotion (word) + 1 word translate
> Update geeksay.js (new translate words)

- geeksay.js
Added 16 translations and 1 quote
> Added translations and a quote

- geeksay.js
> added geek quote

- geeksay.js
`Live, Laugh, Love` translates to `Live, Laugh, <3` which seemed fitting enough. Also added a couple translations that I thought of while I was in there.
> Add "Live, Laugh, Love" as a quote and a couple translations

- index.html
Provided a scroll feature to the output text box that allows for the box to contain a string such as 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' without going past the box shape. Box resizes if space is present between strings.
> Fixed overflow problem with output text box

- geeksay.js
Added "style" and "developer" translations.
#1
> Added translations

- geeksay.js
Added new translations and quotes #1  #5
> Added new Translations and Quotes

- index.html
added spell check attributes to the text area
fixes #29
> added spell check attributes to the text area

- geeksay.js
#5  - added quotes "out of the blue " --> "out of the #0000ff" and "caught red-handed" --> "caught #ff0000 handed"
> added two new quotes

- geeksay.js
- index.html
The main translation logic has been changed and the styling has been updated.
Everything works fine though.
> Serious changes in index.html

- geeksay.js
> Added 2 quotes

- index.html
I added a "copy button" so when the user clicks on that button the translated quote will be copied to our clipboard!
Below is a video of how this button will work:
https://user-images.githubusercontent.com/94648837/191030880-4ce56884-6c27-4b76-b1a1-8f80d4bbae32.mov
> Add a "copy button".

- geeksay.js
99 little bugs in the code. 99 little bugs in the code. Take one down, patch it around. 127 little bugs in the code
> first contribution - bugs

- index.html
added Geeksay Animated `heading` text with changing `::-webkit-scrollbar` size, customized it and added border radius to it
> Update index.html for hacktoberfest 22

- geeksay.js
Just added some quotes & translations after sync fork
> First Contribution Completed

- test/geeksay.test.js
Please add hacktoberfest-accepted lable
> New test case added ++++++

- geeksay.js
- index.html
Changed and wrote a few code in js file to convert any numerical number to its binary form until and unless any special character is added next to including text
> Translation issue while reading numeric values

- geeksay.js
- index.html
added a bunch of translation and also fixed a typo in main index fill for the css part
> translation added

- geeksay.js
> qoute added

- geeksay.js
- index.html
Just made margin responsive for mobile approach
> Edited margin of Textarea

- index.html
solved #355 
copy button is improved.
> Copy button improved and few other tweaks

- geeksay.js
I added new quotes and created a PR
"Everything is under control" and "Give me a break"
Please check
> Added new Quotes

- geeksay.js
Added the following translations:
- comment: "//comment"
- table: "<table>"
- form: "<form>"
- input: "<input>"
- select: "<select>"
- leave: "alt+f4"
- mistake: "ERROR"
Feel free to modify these additions if necessary
> Add translations

- index.html
Fixes #380 
Improved the responsiveness of the website around the buttons with some minor modifications in the CSS.
> Improve the Mobile Responsive Version #380

- geeksay.js
Thank You for reading my additions
> Dhruv Bansal

- geeksay.js
Issue #5 :-
I have added some new quotes 
Please see to it and merge it as soon as possible for HacktoberFest 2022
> Added some new quotes

- geeksay.js
- index.html
Fixes the Issue #380 
I created the Issue and was assigned the same #380 
Someone tweaked the file geeksay.js with syntax errors, causing the website to not run properly. I solved that very minor syntax error.
Rectified the error associated with the Twitter URL as it wasn't converting # and Space to URL Encode.
Added Facebook & Twitter buttons below the output box. Copy button stays inline at the top of the output box. Also, improved the responsiveness a lot.
> Improve the Mobile Responsive Version & Add Social Buttons

- index.html
As mentioned in the issues, the font color and size are changed so that it is more highlighted in the dark background
> Changed color of some elements so that it is more visible in the dark background

- README.md
This is an update to the readme file pointing out missing information about the project and adding the same
> Update readme file with better description of this project

- geeksay.js
I added a new cool quote and necessary translation for it in geeksay.js file
> Added a cool translation and a quote in geeksay.js file

- geeksay.js
Add gandalf quote "shall not pass"
> add new geek quote
